spring.datasource.url=jdbc:mysql://localhost:3306/personDB
spring.datasource.username=chethan
spring.datasource.password=chethan
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
server.error.include-message=always